spring:
  application:
    name: simpleexchange
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev
  jpa:
    open-in-view: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/simple_exchange_db
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

clients:
  nbp:
    url: http://api.nbp.pl/api